name: Playwright Java Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    env:
      TestingEnv: demoblaze
      HEADLESS: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Install Playwright Browsers
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run Tests
        run: mvn test -Dcucumber.filter.tags="@smoke" -Denv=${{ env.TestingEnv }} -Dheadless=${{env.HEADLESS}}

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from GitHub Actions
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Check Allure History
        if: always()
        run: |
          if [ -d "allure-history" ]; then
            echo "Allure history found, proceeding to deploy."
          else
            echo "Allure history not found! Creating empty directory to avoid deploy failure."
            mkdir -p allure-history
            touch allure-history/.nojekyll
          fi

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-history
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "Deploy Allure Report [skip ci]"

      - name: GitHub Job Summary
        if: always()
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "ðŸš€ Environment: ${{ env.TestingEnv }}" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Tests completed. Check the Allure Report for detailed results." >> $GITHUB_STEP_SUMMARY

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ env.TestingEnv }}-smoke
          path: |
            target/cucumber-report.html
            target/cucumber.json
            allure-report/
            allure-history/
            target/traces/
            target/screenshots/
