name: Playwright Java Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    env:
      TestingEnv: demoblaze
      HEADLESS: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Install Playwright Browsers
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run Tests
        run: mvn test -Dcucumber.filter.tags="@smoke" -Denv=${{ env.TestingEnv }} -Dheadless=${{env.HEADLESS}}

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from GitHub Actions
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Check and Prepare Allure History
        if: always()
        run: |
          # If allure-history doesn't exist, create it.
          # If it exists but is empty, add a placeholder to ensure git has something to commit.
          mkdir -p allure-history
          if [ -z "$(ls -A allure-history)" ]; then
            echo "<html><body><h1>Allure Report is being initialized. Please check back after next run.</h1></body></html>" > allure-history/index.html
          fi
          touch allure-history/.nojekyll

      - name: Deploy to GitHub Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: allure-history
          clean: true # Automatically remove old files if any

      - name: GitHub Job Summary
        if: always()
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "ðŸš€ Environment: ${{ env.TestingEnv }}" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Tests completed. Check the Allure Report for detailed results." >> $GITHUB_STEP_SUMMARY

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ env.TestingEnv }}-smoke
          path: |
            target/cucumber-report.html
            target/cucumber.json
            allure-report/
            allure-history/
            target/traces/
            target/screenshots/
